apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: test-header
  namespace: testr
spec:
  gatewayClassName: hedui-gateway-class
  listeners:
    - name: foo-http
      protocol: HTTP
      port: 80
      hostname: header.example.com
      routeConfig:
      requestHeadersToAdd:
      - header:
          key: My-Header
          value: My-Value
        append: true
